require 'twitter'
require 'feedzirra'
require_relative 'twithub/entry_builder_methods'
require_relative 'twithub/feed_entry'
require_relative 'twithub/twitter'
require_relative 'twithub/github'
require_relative 'twithub/twitter_entry'
require_relative 'twithub/github_entry'
